

CREATE TABLE Users (
	ID VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	ROLE VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DATE_CREATION DATE NOT NULL CHECK (DATE_CREATION >= getdate())
);


CREATE TABLE Test_Cases(
	ID INTEGER PRIMARY KEY IDENTITY,
	USER_ID VARCHAR(50) REFERENCES Users(ID) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL,
	STEPS VARCHAR(500) NOT NULL,
	EXPECTED_RESULT VARCHAR(50) NOT NULL,
	PRIORITY INTEGER NOT NULL CHECK (PRIORITY > 0 AND PRIORITY < 11),
	STATUS VARCHAR(50) NOT NULL
);

CREATE TABLE Test_Suite(
	ID INTEGER PRIMARY KEY IDENTITY,
	TEST_CASE INTEGER REFERENCES Test_Cases(ID) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL
);

CREATE TABLE Test_Report(
	ID INTEGER PRIMARY KEY IDENTITY,
	TEST_SUITE INTEGER REFERENCES Test_Suite(ID) NOT NULL,
	CREATION_DATE DATE NOT NULL CHECK (CREATION_DATE >= getdate()),
	OVERALL_STATISTICS VARCHAR(150) NOT NULL
);

CREATE TABLE Test_Run(
	ID INTEGER PRIMARY KEY IDENTITY,
	TEST_SUITE INTEGER REFERENCES Test_Suite(ID) NOT NULL,
	EXECUTION_DATE DATE NOT NULL CHECK (EXECUTION_DATE >= getdate()),
	RESULT VARCHAR(100) NOT NULL	
);

CREATE TABLE Defect (
	ID INTEGER PRIMARY KEY IDENTITY,
	TEST_RUN INTEGER REFERENCES Test_Run(ID) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL,
	SEVERITY VARCHAR(50) NOT NULL,
	PRIORITY INTEGER NOT NULL CHECK (PRIORITY > 0 AND PRIORITY < 11),
	STATUS VARCHAR(50) NOT NULL
);


