

CREATE TABLE Users (
	ID VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL CHECK (NAME LIKE '%[a-zA-Z]%' AND NAME NOT LIKE '%[^a-zA-Z]%'),
	ROLE VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DATE_CREATION DATE NOT NULL CHECK (DATE_CREATION >= getdate())
);
CREATE TABLE Test_Cases(
	ID INTEGER PRIMARY KEY IDENTITY,
	USER_ID VARCHAR(50) REFERENCES Users(ID) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL,
	STEPS VARCHAR(500) NOT NULL,
	EXPECTED_RESULT VARCHAR(50) NOT NULL,
	PRIORITY INTEGER NOT NULL CHECK (PRIORITY > 0 AND PRIORITY < 11),
	STATUS VARCHAR(50) NOT NULL,
	UNIQUE (ID, USER_ID)
);
CREATE TABLE Test_Suite(
	ID INTEGER PRIMARY KEY IDENTITY,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL
);
CREATE TABLE Test_Suite_Cases (
	TEST_SUITE_ID INTEGER REFERENCES Test_Suite(ID),
	TEST_CASE_ID INTEGER REFERENCES Test_Cases(ID),
	PRIMARY KEY (TEST_SUITE_ID, TEST_CASE_ID)
);
CREATE TABLE Test_Run(
	ID INTEGER PRIMARY KEY IDENTITY,
	TEST_SUITE INTEGER UNIQUE REFERENCES Test_Suite(ID) NOT NULL,
	EXECUTION_DATE DATE NOT NULL CHECK (EXECUTION_DATE >= getdate())
);
CREATE TABLE Defect (
	ID INTEGER PRIMARY KEY IDENTITY,
	DESCRIPTION VARCHAR(250) NOT NULL,
	SEVERITY VARCHAR(50) NOT NULL,
	PRIORITY INTEGER NOT NULL CHECK (PRIORITY > 0 AND PRIORITY < 11),
	STATUS VARCHAR(50) NOT NULL
);
CREATE TABLE Test_Report(
	ID INTEGER PRIMARY KEY IDENTITY,
	DEFECT INTEGER UNIQUE REFERENCES Defect(ID),
	TEST_RUN INTEGER REFERENCES Test_Run(ID) NOT NULL,
	CREATION_DATE DATE NOT NULL CHECK (CREATION_DATE >= getdate()),
);