
CREATE PROCEDURE CREATE_TEST_RUN
	@SUITE_ID INTEGER,
	@CASE_ID INTEGER,
	@DATE_START DATE,
	@DATE_END DATE,
	@RESULT VARCHAR(100),
	@DEFECT_ID INTEGER,
	@USER_ID INTEGER
AS
BEGIN
	BEGIN TRY
		INSERT INTO TEST_RUNS(TEST_SUITE_ID, TEST_CASE_ID, DATE_START, DATE_END, RESULT, DEFECT_ID, USER_ID) VALUES (@SUITE_ID, @CASE_ID, @DATE_START, @DATE_END, @RESULT, @DEFECT_ID, @USER_ID);
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;

		SELECT 
			@ErrorMessage = ERROR_MESSAGE(),
			@ErrorSeverity = ERROR_SEVERITY(),
			@ErrorState = ERROR_STATE();

				RAISERROR('Произошла ошибка при создании тестового запуска.', @ErrorSeverity, @ErrorState, @ErrorMessage);
	END CATCH;
END

